{% set name = "openinference-instrumentation-llama-index" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openinference_instrumentation_llama_index-{{ version }}.tar.gz
  sha256: ac4ac639d8ac22efb3684a48f2a67f90070eee7a053ee829ac010cfd3fb2b4ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - hatchling
    - pip
  run:
    - python >=3.8,<3.12
    - opentelemetry-api
    - opentelemetry-instrumentation
    - opentelemetry-semantic-conventions
    - openinference-instrumentation >=0.1.7
    - openinference-semantic-conventions
    - typing-extensions
    - wrapt

test:
  imports:
    - openinference.instrumentation.llama_index

about:
  summary: OpenInference LlamaIndex Instrumentation
  home: https://github.com/Arize-ai/openinference
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - michaelschiff
    - mikeldking
    - RogerHYang
    - axiomofjoy
    - anticorrelator
